### ISSUE TITLE
sideNav materialize-amd not working

### ISSUE THREAD

**Issue by edwinnnss** [max1011/materialize-AMD#1]
when i used 
$(".button-collapse").sideNav();

brower console said 
Uncaught TypeError: $(...).sideNav is not a function

can you help me ?

**Comment by max1011** [comment]
I will check that ASAP

**Comment by max1011** [comment]
What file did you include? From which directory?

**Comment by max1011** [comment]
Did you try to open amdtest html file?, does it log anything? 
People say that the test works including sidenav

**Comment by max1011** [comment]
i have to close looks like you don't know how to use , sorry !

**Comment by tusharvikky** [comment]
Do we have to include /js/sidenav.js. I'm using dist/materialize.amd.js.

**Comment by max1011** [comment]
@tusharvikky it's included, no need to include it another time, does it work for you ? try the amdtest html file and tell me if it works

**Comment by tusharvikky** [comment]
@max1011  Got it to work. Apparently it requires hammer and jquery.hammer. Found it the hard way. :P
