### ISSUE TITLE
Date Picker not unfocusing correctly (x-post)

### ISSUE THREAD

**Issue by isaachinman** [max1011/materialize-AMD#2]
Hey there, I've already [posted this on the main repo](https://github.com/Dogfalo/materialize/issues/2075), but there's a significant issue with the Date Picker. If you can figure it out and patch it here, that'd be great too!

**Comment by max1011** [comment]
can you please include an image ?

**Comment by isaachinman** [comment]
@max1011 Include an image of what?

**Comment by max1011** [comment]
@isaachinman an image that shows the date picker not working, what is the real issue ? , can u explain more??, 
i had one issue with the date picker my self but i fixed it for my own project with css, i don't know if ur issue is similar or what

**Comment by max1011** [comment]
@isaachinman i checked it now , on their website and there is a scroll bar that appears when unfocusing , is that what u are talking about ?

**Comment by isaachinman** [comment]
@max1011 It's a js issue, the modal doesn't properly unfocus.You can find the original issue [here](https://github.com/amsul/pickadate.js/issues/770). I came up with a small CSS fix to partially fix it, but not entirely.

**Comment by max1011** [comment]
for everyone having this problem the solution is [here](https://github.com/amsul/pickadate.js/issues/770)

**Comment by max1011** [comment]
this problem is solved a while ago , i have to close , if this happens again i will reopen

**Comment by ShaheensWeb** [comment]
Still need a solution to this, the CSS covers cases in which the user clicks away from the picker but any clicking of actual dates/buttons on the picker and toggling of browser tabs still causes the same issue.
